var searchData=
[
  ['v_0',['V',['../classsf_1_1_joystick.html#a48db337092c2e263774f94de6d50baa7a1ee0dbe4e1d77261b4ce772d1aed6d37',1,'sf::Joystick::V'],['../structsf_1_1_keyboard_1_1_scan.html#aa42fbf6954d6f81f7606e566c7abe875a663fc44f2227e8bf19654ea3b4667e7c',1,'sf::Keyboard::Scan::V'],['../classsf_1_1_keyboard.html#acb4cacd7cc5802dec45724cf3314a142aede3e8846870eab66719875d1b21057e',1,'sf::Keyboard::V']]],
  ['validatemenuitem_3a_1',['validateMenuItem:',['../interface_s_f_window.html#a49a3a95d95836e320fbabf0988fd261c',1,'SFWindow::validateMenuItem:(NSMenuItem *menuItem)'],['../interface_s_f_window.html#a49a3a95d95836e320fbabf0988fd261c',1,'SFWindow::validateMenuItem:(NSMenuItem *menuItem)']]],
  ['validating_20a_20member_20of_20an_20object_2',['Validating a Member of an Object',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md138',1,'Validating a Member of an Object'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md637',1,'Validating a Member of an Object']]],
  ['validating_20the_20value_20pointed_20to_20by_20a_20pointer_20argument_3',['Validating the Value Pointed to by a Pointer Argument',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md139',1,'Validating the Value Pointed to by a Pointer Argument'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md638',1,'Validating the Value Pointed to by a Pointer Argument']]],
  ['value_4',['Value',['../md_build_2__deps_2googletest-src_2docs_2reference_2actions.html#autotoc_md244',1,'Returning a Value'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2actions.html#autotoc_md743',1,'Returning a Value']]],
  ['value_5',['value',['../group__flac__format.html#gaf1bcfcbb17f1e1edb115b002fdbaa70e',1,'FLAC__Subframe_Constant::value'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#value',1,'value']]],
  ['value_20for_20a_20return_20type_6',['Setting the Default Value for a Return Type',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2mocking.html#DefaultValue',1,'']]],
  ['value_20not_20ignored_20as_20it_20ought_20to_20be_20what_20does_20this_20mean_7',['value not ignored as it ought to be What does this mean',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md91',1,'My compiler complains &quot;void value not ignored as it ought to be.&quot; What does this mean?'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md590',1,'My compiler complains &quot;void value not ignored as it ought to be.&quot; What does this mean?']]],
  ['value_20parameterized_20abstract_20tests_8',['Value Parameterized Abstract Tests',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md47',1,'Creating Value-Parameterized Abstract Tests'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md546',1,'Creating Value-Parameterized Abstract Tests']]],
  ['value_20parameterized_20test_20parameters_9',['Value Parameterized Test Parameters',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md48',1,'Specifying Names for Value-Parameterized Test Parameters'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md547',1,'Specifying Names for Value-Parameterized Test Parameters']]],
  ['value_20parameterized_20tests_10',['Value Parameterized Tests',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md46',1,'How to Write Value-Parameterized Tests'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md545',1,'How to Write Value-Parameterized Tests'],['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md45',1,'Value-Parameterized Tests'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md544',1,'Value-Parameterized Tests']]],
  ['value_20parameterized_20tests_11',['value parameterized tests',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md85',1,'I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md584',1,'I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?']]],
  ['value_20pointed_20to_20by_20a_20pointer_20argument_12',['Value Pointed to by a Pointer Argument',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md139',1,'Validating the Value Pointed to by a Pointer Argument'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md638',1,'Validating the Value Pointed to by a Pointer Argument']]],
  ['value_20what_20s_20going_20on_13',['value What s going on',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md95',1,'My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md594',1,'My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?']]],
  ['value_20when_20i_20call_20run_5fall_5ftests_20why_14',['value when I call RUN_ALL_TESTS Why',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md94',1,'My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md593',1,'My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?']]],
  ['value_5fparam_20testinfo_3a_3avalue_5fparam_15',['value_param TestInfo::value_param',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md306',1,'value_param {TestInfo::value_param}'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md805',1,'value_param {TestInfo::value_param}']]],
  ['valuearray_16',['ValueArray',['../classtesting_1_1internal_1_1_value_array.html',1,'testing::internal']]],
  ['valueparamtest_17',['ValueParamTest',['../class_value_param_test.html',1,'']]],
  ['values_18',['Values',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md178',1,'Teaching gMock How to Print Your Values'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md677',1,'Teaching gMock How to Print Your Values'],['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md27',1,'Teaching googletest How to Print Your Values'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md526',1,'Teaching googletest How to Print Your Values']]],
  ['values_20exactly_19',['Values Exactly',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md130',1,'Matching Argument Values Exactly'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md629',1,'Matching Argument Values Exactly']]],
  ['values_20from_20mock_20methods_20',['Values from Mock Methods',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md148',1,'Returning Live Values from Mock Methods'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md647',1,'Returning Live Values from Mock Methods']]],
  ['valuesgenerator_21',['ValuesGenerator',['../class_catch_1_1_values_generator.html',1,'Catch']]],
  ['valuesiniteratorrangegenerator_22',['ValuesInIteratorRangeGenerator',['../classtesting_1_1internal_1_1_values_in_iterator_range_generator.html',1,'testing::internal']]],
  ['variables_23',['variables',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md99',1,'Why should I prefer test fixtures over global variables?'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md598',1,'Why should I prefer test fixtures over global variables?']]],
  ['variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_24',['variables but I did define them in the class body What s wrong',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md89',1,'The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md588',1,'The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?']]],
  ['variadic_20function_25',['variadic function',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md182',1,'Can I mock a variadic function?'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md681',1,'Can I mock a variadic function?']]],
  ['various_20build_20systems_26',['various build systems',['../md_build_2__deps_2googletest-src_2docs_2pkgconfig.html',1,'Using GoogleTest from various build systems'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2pkgconfig.html',1,'Using GoogleTest from various build systems']]],
  ['vec2_27',['Vec2',['../namespacesf_1_1_glsl.html#abfcb09fe753e2d3afdf5b34ead5ac998',1,'sf::Glsl']]],
  ['vec3_28',['Vec3',['../namespacesf_1_1_glsl.html#a054bd0a821d072e08de6c358de9f67ad',1,'sf::Glsl']]],
  ['vector_29',['vector',['../classtesting_1_1gmock__matchers__test_1_1vector.html',1,'testing::gmock_matchers_test::vector'],['../classtesting_1_1gtest__printers__test_1_1vector.html',1,'testing::gtest_printers_test::vector'],['../classvector.html',1,'vector']]],
  ['vector2_30',['Vector2',['../struct_pacman_1_1_vector2.html',1,'Pacman::Vector2'],['../classsf_1_1_vector2.html',1,'sf::Vector2&lt; T &gt;'],['../classsf_1_1_vector2.html#a58c32383b5291380db4b43a289f75988',1,'sf::Vector2::Vector2()'],['../classsf_1_1_vector2.html#aed26a72164e59e8a4a0aeee2049568f1',1,'sf::Vector2::Vector2(T X, T Y)'],['../classsf_1_1_vector2.html#a3da455e0ae3f8ff6d2fe36d10b332d10',1,'sf::Vector2::Vector2(const Vector2&lt; U &gt; &amp;vector)'],['../classsf_1_1_vector2.html#a58c32383b5291380db4b43a289f75988',1,'sf::Vector2::Vector2()'],['../classsf_1_1_vector2.html#aed26a72164e59e8a4a0aeee2049568f1',1,'sf::Vector2::Vector2(T X, T Y)'],['../classsf_1_1_vector2.html#a3da455e0ae3f8ff6d2fe36d10b332d10',1,'sf::Vector2::Vector2(const Vector2&lt; U &gt; &amp;vector)']]],
  ['vector2_3c_20bool_20_3e_31',['Vector2&lt; bool &gt;',['../classsf_1_1_vector2.html',1,'sf']]],
  ['vector2_3c_20float_20_3e_32',['Vector2&lt; float &gt;',['../classsf_1_1_vector2.html',1,'sf']]],
  ['vector2_3c_20int_20_3e_33',['Vector2&lt; int &gt;',['../classsf_1_1_vector2.html',1,'sf']]],
  ['vector2_3c_20unsigned_20int_20_3e_34',['Vector2&lt; unsigned int &gt;',['../classsf_1_1_vector2.html',1,'sf']]],
  ['vector2test_35',['Vector2Test',['../class_vector2_test.html',1,'']]],
  ['vector3_36',['Vector3',['../classsf_1_1_vector3.html',1,'sf::Vector3&lt; T &gt;'],['../classsf_1_1_vector3.html#aee8be1985c6e45e381ad4071265636f9',1,'sf::Vector3::Vector3()'],['../classsf_1_1_vector3.html#a99ed75b68f58adfa3e9fa0561b424bf6',1,'sf::Vector3::Vector3(T X, T Y, T Z)'],['../classsf_1_1_vector3.html#adb2b2e150025e97ccfa96219bbed59d1',1,'sf::Vector3::Vector3(const Vector3&lt; U &gt; &amp;vector)'],['../classsf_1_1_vector3.html#aee8be1985c6e45e381ad4071265636f9',1,'sf::Vector3::Vector3()'],['../classsf_1_1_vector3.html#a99ed75b68f58adfa3e9fa0561b424bf6',1,'sf::Vector3::Vector3(T X, T Y, T Z)'],['../classsf_1_1_vector3.html#adb2b2e150025e97ccfa96219bbed59d1',1,'sf::Vector3::Vector3(const Vector3&lt; U &gt; &amp;vector)']]],
  ['vector3_3c_20bool_20_3e_37',['Vector3&lt; bool &gt;',['../classsf_1_1_vector3.html',1,'sf']]],
  ['vector3_3c_20float_20_3e_38',['Vector3&lt; float &gt;',['../classsf_1_1_vector3.html',1,'sf']]],
  ['vector3_3c_20int_20_3e_39',['Vector3&lt; int &gt;',['../classsf_1_1_vector3.html',1,'sf']]],
  ['vector4_40',['Vector4',['../structsf_1_1priv_1_1_vector4.html',1,'sf::priv::Vector4&lt; T &gt;'],['../struct_vector4.html',1,'Vector4&lt; T &gt;'],['../struct_vector4.html#afdef97d94e5697622b5322637028accf',1,'Vector4::Vector4()'],['../struct_vector4.html#ae099ed0a6d7d78ed38ac023d0e4cec25',1,'Vector4::Vector4(T X, T Y, T Z, T W)'],['../struct_vector4.html#a6413d8b504d7fdfbb600a0caf9c90cc2',1,'Vector4::Vector4(const Vector4&lt; U &gt; &amp;other)'],['../struct_vector4.html#af1da65a743ddbb5c779b41eae766c00d',1,'Vector4::Vector4(const Color &amp;color)'],['../struct_vector4.html#afdef97d94e5697622b5322637028accf',1,'Vector4::Vector4()'],['../struct_vector4.html#ae099ed0a6d7d78ed38ac023d0e4cec25',1,'Vector4::Vector4(T X, T Y, T Z, T W)'],['../struct_vector4.html#a6413d8b504d7fdfbb600a0caf9c90cc2',1,'Vector4::Vector4(const Vector4&lt; U &gt; &amp;other)'],['../struct_vector4.html#af1da65a743ddbb5c779b41eae766c00d',1,'Vector4::Vector4(const Color &amp;color)']]],
  ['vector4_3c_20bool_20_3e_41',['Vector4&lt; bool &gt;',['../structsf_1_1priv_1_1_vector4.html',1,'sf::priv']]],
  ['vector4_3c_20float_20_3e_42',['Vector4&lt; float &gt;',['../structsf_1_1priv_1_1_vector4.html',1,'sf::priv']]],
  ['vector4_3c_20int_20_3e_43',['Vector4&lt; int &gt;',['../structsf_1_1priv_1_1_vector4.html',1,'sf::priv']]],
  ['vendorid_44',['vendorId',['../structsf_1_1_joystick_1_1_identification.html#a827caf37a56492e3430e5ca6b15b5e9f',1,'sf::Joystick::Identification']]],
  ['verification_45',['Verification',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md162',1,'Forcing a Verification'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md661',1,'Forcing a Verification']]],
  ['verifying_20and_20resetting_20a_20mock_46',['Verifying and Resetting a Mock',['../md_build_2__deps_2googletest-src_2docs_2gmock__cheat__sheet.html#autotoc_md115',1,'Verifying and Resetting a Mock'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cheat__sheet.html#autotoc_md614',1,'Verifying and Resetting a Mock']]],
  ['verifying_20complex_20arguments_47',['Verifying Complex Arguments',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#SaveArgVerify',1,'']]],
  ['version_48',['Version',['../dir_001a0f336d1d0a6c17b1be78e41a6b36.html#autotoc_md399',1,'C++ Standard Version'],['../dir_c3fcd705cb2f7b6b5193739f9f3f9966.html#autotoc_md898',1,'C++ Standard Version']]],
  ['versionnotsupported_49',['VersionNotSupported',['../classsf_1_1_http_1_1_response.html#a663e071978e30fbbeb20ed045be874d8a58a53b15904ee0204512cff7b4cb3dc7',1,'sf::Http::Response']]],
  ['versions_50',['Porting Guide for New Versions',['../group__porting.html',1,'']]],
  ['vertex_51',['Vertex',['../classsf_1_1_vertex.html',1,'sf::Vertex'],['../classsf_1_1_shader.html#afaa1aa65e5de37b74d047da9def9f9b3ac6677cff2fb888f93e247591d886a791',1,'sf::Shader::Vertex'],['../classsf_1_1_vertex.html#a6b4c79cd69f7ec1296fede536f39e9c8',1,'sf::Vertex::Vertex()'],['../classsf_1_1_vertex.html#a4dccc5c351b73b6fac169fe442535b40',1,'sf::Vertex::Vertex(const Vector2f &amp;thePosition)'],['../classsf_1_1_vertex.html#a70b0679b4ec531d5bd1a7d0225c7321a',1,'sf::Vertex::Vertex(const Vector2f &amp;thePosition, const Color &amp;theColor)'],['../classsf_1_1_vertex.html#ab9bf849c4c0d82d09bf5bece23d2456a',1,'sf::Vertex::Vertex(const Vector2f &amp;thePosition, const Vector2f &amp;theTexCoords)'],['../classsf_1_1_vertex.html#ad5943f2b3cbc64b6e714bb37ccaf4960',1,'sf::Vertex::Vertex(const Vector2f &amp;thePosition, const Color &amp;theColor, const Vector2f &amp;theTexCoords)'],['../classsf_1_1_vertex.html#a6b4c79cd69f7ec1296fede536f39e9c8',1,'sf::Vertex::Vertex()'],['../classsf_1_1_vertex.html#a4dccc5c351b73b6fac169fe442535b40',1,'sf::Vertex::Vertex(const Vector2f &amp;thePosition)'],['../classsf_1_1_vertex.html#a70b0679b4ec531d5bd1a7d0225c7321a',1,'sf::Vertex::Vertex(const Vector2f &amp;thePosition, const Color &amp;theColor)'],['../classsf_1_1_vertex.html#ab9bf849c4c0d82d09bf5bece23d2456a',1,'sf::Vertex::Vertex(const Vector2f &amp;thePosition, const Vector2f &amp;theTexCoords)'],['../classsf_1_1_vertex.html#ad5943f2b3cbc64b6e714bb37ccaf4960',1,'sf::Vertex::Vertex(const Vector2f &amp;thePosition, const Color &amp;theColor, const Vector2f &amp;theTexCoords)']]],
  ['vertexarray_52',['VertexArray',['../classsf_1_1_vertex_array.html',1,'sf::VertexArray'],['../classsf_1_1_vertex_array.html#a15729e01df8fc0021f9774dfb56295c1',1,'sf::VertexArray::VertexArray()'],['../classsf_1_1_vertex_array.html#a4bb1c29a0e3354a035075899d84f02f9',1,'sf::VertexArray::VertexArray(PrimitiveType type, std::size_t vertexCount=0)'],['../classsf_1_1_vertex_array.html#a15729e01df8fc0021f9774dfb56295c1',1,'sf::VertexArray::VertexArray()'],['../classsf_1_1_vertex_array.html#a4bb1c29a0e3354a035075899d84f02f9',1,'sf::VertexArray::VertexArray(PrimitiveType type, std::size_t vertexCount=0)']]],
  ['vertexbuffer_53',['VertexBuffer',['../classsf_1_1_vertex_buffer.html',1,'sf::VertexBuffer'],['../classsf_1_1_vertex_buffer.html#aba8836c571cef25a0f80e478add1560a',1,'sf::VertexBuffer::VertexBuffer()'],['../classsf_1_1_vertex_buffer.html#a3f51dcd61dac52be54ba7b22ebdea7c8',1,'sf::VertexBuffer::VertexBuffer(PrimitiveType type)'],['../classsf_1_1_vertex_buffer.html#af2dce0a43e061e5f91b97cf7267427e3',1,'sf::VertexBuffer::VertexBuffer(Usage usage)'],['../classsf_1_1_vertex_buffer.html#a326a5c89f1ba01b51b323535494434e8',1,'sf::VertexBuffer::VertexBuffer(PrimitiveType type, Usage usage)'],['../classsf_1_1_vertex_buffer.html#a2f2ff1e218cfc749b87f8873e23c016b',1,'sf::VertexBuffer::VertexBuffer(const VertexBuffer &amp;copy)'],['../classsf_1_1_vertex_buffer.html#aba8836c571cef25a0f80e478add1560a',1,'sf::VertexBuffer::VertexBuffer()'],['../classsf_1_1_vertex_buffer.html#a3f51dcd61dac52be54ba7b22ebdea7c8',1,'sf::VertexBuffer::VertexBuffer(PrimitiveType type)'],['../classsf_1_1_vertex_buffer.html#af2dce0a43e061e5f91b97cf7267427e3',1,'sf::VertexBuffer::VertexBuffer(Usage usage)'],['../classsf_1_1_vertex_buffer.html#a326a5c89f1ba01b51b323535494434e8',1,'sf::VertexBuffer::VertexBuffer(PrimitiveType type, Usage usage)'],['../classsf_1_1_vertex_buffer.html#a2f2ff1e218cfc749b87f8873e23c016b',1,'sf::VertexBuffer::VertexBuffer(const VertexBuffer &amp;copy)']]],
  ['verticalwheel_54',['VerticalWheel',['../classsf_1_1_mouse.html#a60dd479a43f26f200e7957aa11803ff4a8964269d4e4c0efc6cdefaad1b700250',1,'sf::Mouse']]],
  ['veryloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooogname_55',['VeryLoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooogName',['../class_very_loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo570db76e21fa868abfe0f6323a68c9ba.html',1,'']]],
  ['videomode_56',['VideoMode',['../classsf_1_1_video_mode.html',1,'sf::VideoMode'],['../classsf_1_1_video_mode.html#a04c9417e5c304510bef5f6aeb03f6ce1',1,'sf::VideoMode::VideoMode()'],['../classsf_1_1_video_mode.html#a46c35ed41de9e115661dcd529d64e9d3',1,'sf::VideoMode::VideoMode(unsigned int modeWidth, unsigned int modeHeight, unsigned int modeBitsPerPixel=32)'],['../classsf_1_1_video_mode.html#a04c9417e5c304510bef5f6aeb03f6ce1',1,'sf::VideoMode::VideoMode()'],['../classsf_1_1_video_mode.html#a46c35ed41de9e115661dcd529d64e9d3',1,'sf::VideoMode::VideoMode(unsigned int modeWidth, unsigned int modeHeight, unsigned int modeBitsPerPixel=32)']]],
  ['videomodeimpl_57',['VideoModeImpl',['../classsf_1_1priv_1_1_video_mode_impl.html',1,'sf::priv']]],
  ['view_58',['View',['../classsf_1_1_view.html',1,'sf::View'],['../classsf_1_1_view.html#a28c38308ff089ae5bdacd001d12286d3',1,'sf::View::View()'],['../classsf_1_1_view.html#a1d63bc49e041b3b1ff992bb6430e1326',1,'sf::View::View(const FloatRect &amp;rectangle)'],['../classsf_1_1_view.html#afdaf84cfc910ef160450d63603457ea4',1,'sf::View::View(const Vector2f &amp;center, const Vector2f &amp;size)'],['../classsf_1_1_view.html#a28c38308ff089ae5bdacd001d12286d3',1,'sf::View::View()'],['../classsf_1_1_view.html#a1d63bc49e041b3b1ff992bb6430e1326',1,'sf::View::View(const FloatRect &amp;rectangle)'],['../classsf_1_1_view.html#afdaf84cfc910ef160450d63603457ea4',1,'sf::View::View(const Vector2f &amp;center, const Vector2f &amp;size)']]],
  ['viewdidendliveresize_59',['viewDidEndLiveResize',['../category_s_f_open_g_l_view_07_08.html#ac1c9c9c351c92b2086698bd070a58359',1,'SFOpenGLView()::viewDidEndLiveResize()'],['../category_s_f_open_g_l_view_07_08.html#ac1c9c9c351c92b2086698bd070a58359',1,'SFOpenGLView()::viewDidEndLiveResize()']]],
  ['virtual_20methods_60',['Mocking Non-virtual Methods',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#MockingNonVirtualMethods',1,'']]],
  ['vision_20into_20mock_20calls_61',['Vision into Mock Calls',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md165',1,'Gaining Super Vision into Mock Calls'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md664',1,'Gaining Super Vision into Mock Calls']]],
  ['visual_20c_20runs_20out_20of_20memory_20when_20compiling_20it_20what_20can_20i_20do_62',['Visual C runs out of memory when compiling it What can I do',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md198',1,'I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md697',1,'I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?']]],
  ['visual_20studio_20dynamic_20vs_20static_20runtimes_63',['Visual Studio Dynamic vs Static Runtimes',['../dir_001a0f336d1d0a6c17b1be78e41a6b36.html#autotoc_md398',1,'Visual Studio Dynamic vs Static Runtimes'],['../dir_c3fcd705cb2f7b6b5193739f9f3f9966.html#autotoc_md897',1,'Visual Studio Dynamic vs Static Runtimes']]],
  ['visual_20studio_20vs_20method_64',['Visual Studio (VS) method',['../md__r_e_a_d_m_e.html#autotoc_md1003',1,'']]],
  ['vk_5floader_5fdata_65',['VK_LOADER_DATA',['../union_v_k___l_o_a_d_e_r___d_a_t_a.html',1,'']]],
  ['vkacquirenextimageinfokhr_66',['VkAcquireNextImageInfoKHR',['../struct_vk_acquire_next_image_info_k_h_r.html',1,'']]],
  ['vkallocationcallbacks_67',['VkAllocationCallbacks',['../struct_vk_allocation_callbacks.html',1,'']]],
  ['vkandroidhardwarebufferformatpropertiesandroid_68',['VkAndroidHardwareBufferFormatPropertiesANDROID',['../struct_vk_android_hardware_buffer_format_properties_a_n_d_r_o_i_d.html',1,'']]],
  ['vkandroidhardwarebufferpropertiesandroid_69',['VkAndroidHardwareBufferPropertiesANDROID',['../struct_vk_android_hardware_buffer_properties_a_n_d_r_o_i_d.html',1,'']]],
  ['vkandroidhardwarebufferusageandroid_70',['VkAndroidHardwareBufferUsageANDROID',['../struct_vk_android_hardware_buffer_usage_a_n_d_r_o_i_d.html',1,'']]],
  ['vkandroidsurfacecreateinfokhr_71',['VkAndroidSurfaceCreateInfoKHR',['../struct_vk_android_surface_create_info_k_h_r.html',1,'']]],
  ['vkapplicationinfo_72',['VkApplicationInfo',['../struct_vk_application_info.html',1,'']]],
  ['vkattachmentdescription_73',['VkAttachmentDescription',['../struct_vk_attachment_description.html',1,'']]],
  ['vkattachmentdescription2khr_74',['VkAttachmentDescription2KHR',['../struct_vk_attachment_description2_k_h_r.html',1,'']]],
  ['vkattachmentreference_75',['VkAttachmentReference',['../struct_vk_attachment_reference.html',1,'']]],
  ['vkattachmentreference2khr_76',['VkAttachmentReference2KHR',['../struct_vk_attachment_reference2_k_h_r.html',1,'']]],
  ['vkattachmentsamplelocationsext_77',['VkAttachmentSampleLocationsEXT',['../struct_vk_attachment_sample_locations_e_x_t.html',1,'']]],
  ['vkbaseinstructure_78',['VkBaseInStructure',['../struct_vk_base_in_structure.html',1,'']]],
  ['vkbaseoutstructure_79',['VkBaseOutStructure',['../struct_vk_base_out_structure.html',1,'']]],
  ['vkbindbuffermemorydevicegroupinfo_80',['VkBindBufferMemoryDeviceGroupInfo',['../struct_vk_bind_buffer_memory_device_group_info.html',1,'']]],
  ['vkbindbuffermemoryinfo_81',['VkBindBufferMemoryInfo',['../struct_vk_bind_buffer_memory_info.html',1,'']]],
  ['vkbindimagememorydevicegroupinfo_82',['VkBindImageMemoryDeviceGroupInfo',['../struct_vk_bind_image_memory_device_group_info.html',1,'']]],
  ['vkbindimagememoryinfo_83',['VkBindImageMemoryInfo',['../struct_vk_bind_image_memory_info.html',1,'']]],
  ['vkbindimagememoryswapchaininfokhr_84',['VkBindImageMemorySwapchainInfoKHR',['../struct_vk_bind_image_memory_swapchain_info_k_h_r.html',1,'']]],
  ['vkbindimageplanememoryinfo_85',['VkBindImagePlaneMemoryInfo',['../struct_vk_bind_image_plane_memory_info.html',1,'']]],
  ['vkbindsparseinfo_86',['VkBindSparseInfo',['../struct_vk_bind_sparse_info.html',1,'']]],
  ['vkbuffercopy_87',['VkBufferCopy',['../struct_vk_buffer_copy.html',1,'']]],
  ['vkbuffercreateinfo_88',['VkBufferCreateInfo',['../struct_vk_buffer_create_info.html',1,'']]],
  ['vkbufferimagecopy_89',['VkBufferImageCopy',['../struct_vk_buffer_image_copy.html',1,'']]],
  ['vkbuffermemorybarrier_90',['VkBufferMemoryBarrier',['../struct_vk_buffer_memory_barrier.html',1,'']]],
  ['vkbuffermemoryrequirementsinfo2_91',['VkBufferMemoryRequirementsInfo2',['../struct_vk_buffer_memory_requirements_info2.html',1,'']]],
  ['vkbufferviewcreateinfo_92',['VkBufferViewCreateInfo',['../struct_vk_buffer_view_create_info.html',1,'']]],
  ['vkchainheader_93',['VkChainHeader',['../struct_vk_chain_header.html',1,'']]],
  ['vkcheckpointdatanv_94',['VkCheckpointDataNV',['../struct_vk_checkpoint_data_n_v.html',1,'']]],
  ['vkclearattachment_95',['VkClearAttachment',['../struct_vk_clear_attachment.html',1,'']]],
  ['vkclearcolorvalue_96',['VkClearColorValue',['../union_vk_clear_color_value.html',1,'']]],
  ['vkcleardepthstencilvalue_97',['VkClearDepthStencilValue',['../struct_vk_clear_depth_stencil_value.html',1,'']]],
  ['vkclearrect_98',['VkClearRect',['../struct_vk_clear_rect.html',1,'']]],
  ['vkclearvalue_99',['VkClearValue',['../union_vk_clear_value.html',1,'']]],
  ['vkcmdprocesscommandsinfonvx_100',['VkCmdProcessCommandsInfoNVX',['../struct_vk_cmd_process_commands_info_n_v_x.html',1,'']]],
  ['vkcmdreservespaceforcommandsinfonvx_101',['VkCmdReserveSpaceForCommandsInfoNVX',['../struct_vk_cmd_reserve_space_for_commands_info_n_v_x.html',1,'']]],
  ['vkcommandbufferallocateinfo_102',['VkCommandBufferAllocateInfo',['../struct_vk_command_buffer_allocate_info.html',1,'']]],
  ['vkcommandbufferbegininfo_103',['VkCommandBufferBeginInfo',['../struct_vk_command_buffer_begin_info.html',1,'']]],
  ['vkcommandbufferinheritanceconditionalrenderinginfoext_104',['VkCommandBufferInheritanceConditionalRenderingInfoEXT',['../struct_vk_command_buffer_inheritance_conditional_rendering_info_e_x_t.html',1,'']]],
  ['vkcommandbufferinheritanceinfo_105',['VkCommandBufferInheritanceInfo',['../struct_vk_command_buffer_inheritance_info.html',1,'']]],
  ['vkcommandpoolcreateinfo_106',['VkCommandPoolCreateInfo',['../struct_vk_command_pool_create_info.html',1,'']]],
  ['vkcomponentmapping_107',['VkComponentMapping',['../struct_vk_component_mapping.html',1,'']]],
  ['vkcomputepipelinecreateinfo_108',['VkComputePipelineCreateInfo',['../struct_vk_compute_pipeline_create_info.html',1,'']]],
  ['vkconditionalrenderingbegininfoext_109',['VkConditionalRenderingBeginInfoEXT',['../struct_vk_conditional_rendering_begin_info_e_x_t.html',1,'']]],
  ['vkcopydescriptorset_110',['VkCopyDescriptorSet',['../struct_vk_copy_descriptor_set.html',1,'']]],
  ['vkd3d12fencesubmitinfokhr_111',['VkD3D12FenceSubmitInfoKHR',['../struct_vk_d3_d12_fence_submit_info_k_h_r.html',1,'']]],
  ['vkdebugmarkermarkerinfoext_112',['VkDebugMarkerMarkerInfoEXT',['../struct_vk_debug_marker_marker_info_e_x_t.html',1,'']]],
  ['vkdebugmarkerobjectnameinfoext_113',['VkDebugMarkerObjectNameInfoEXT',['../struct_vk_debug_marker_object_name_info_e_x_t.html',1,'']]],
  ['vkdebugmarkerobjecttaginfoext_114',['VkDebugMarkerObjectTagInfoEXT',['../struct_vk_debug_marker_object_tag_info_e_x_t.html',1,'']]],
  ['vkdebugreportcallbackcreateinfoext_115',['VkDebugReportCallbackCreateInfoEXT',['../struct_vk_debug_report_callback_create_info_e_x_t.html',1,'']]],
  ['vkdebugutilslabelext_116',['VkDebugUtilsLabelEXT',['../struct_vk_debug_utils_label_e_x_t.html',1,'']]],
  ['vkdebugutilsmessengercallbackdataext_117',['VkDebugUtilsMessengerCallbackDataEXT',['../struct_vk_debug_utils_messenger_callback_data_e_x_t.html',1,'']]],
  ['vkdebugutilsmessengercreateinfoext_118',['VkDebugUtilsMessengerCreateInfoEXT',['../struct_vk_debug_utils_messenger_create_info_e_x_t.html',1,'']]],
  ['vkdebugutilsobjectnameinfoext_119',['VkDebugUtilsObjectNameInfoEXT',['../struct_vk_debug_utils_object_name_info_e_x_t.html',1,'']]],
  ['vkdebugutilsobjecttaginfoext_120',['VkDebugUtilsObjectTagInfoEXT',['../struct_vk_debug_utils_object_tag_info_e_x_t.html',1,'']]],
  ['vkdedicatedallocationbuffercreateinfonv_121',['VkDedicatedAllocationBufferCreateInfoNV',['../struct_vk_dedicated_allocation_buffer_create_info_n_v.html',1,'']]],
  ['vkdedicatedallocationimagecreateinfonv_122',['VkDedicatedAllocationImageCreateInfoNV',['../struct_vk_dedicated_allocation_image_create_info_n_v.html',1,'']]],
  ['vkdedicatedallocationmemoryallocateinfonv_123',['VkDedicatedAllocationMemoryAllocateInfoNV',['../struct_vk_dedicated_allocation_memory_allocate_info_n_v.html',1,'']]],
  ['vkdescriptorbufferinfo_124',['VkDescriptorBufferInfo',['../struct_vk_descriptor_buffer_info.html',1,'']]],
  ['vkdescriptorimageinfo_125',['VkDescriptorImageInfo',['../struct_vk_descriptor_image_info.html',1,'']]],
  ['vkdescriptorpoolcreateinfo_126',['VkDescriptorPoolCreateInfo',['../struct_vk_descriptor_pool_create_info.html',1,'']]],
  ['vkdescriptorpoolsize_127',['VkDescriptorPoolSize',['../struct_vk_descriptor_pool_size.html',1,'']]],
  ['vkdescriptorsetallocateinfo_128',['VkDescriptorSetAllocateInfo',['../struct_vk_descriptor_set_allocate_info.html',1,'']]],
  ['vkdescriptorsetlayoutbinding_129',['VkDescriptorSetLayoutBinding',['../struct_vk_descriptor_set_layout_binding.html',1,'']]],
  ['vkdescriptorsetlayoutbindingflagscreateinfoext_130',['VkDescriptorSetLayoutBindingFlagsCreateInfoEXT',['../struct_vk_descriptor_set_layout_binding_flags_create_info_e_x_t.html',1,'']]],
  ['vkdescriptorsetlayoutcreateinfo_131',['VkDescriptorSetLayoutCreateInfo',['../struct_vk_descriptor_set_layout_create_info.html',1,'']]],
  ['vkdescriptorsetlayoutsupport_132',['VkDescriptorSetLayoutSupport',['../struct_vk_descriptor_set_layout_support.html',1,'']]],
  ['vkdescriptorsetvariabledescriptorcountallocateinfoext_133',['VkDescriptorSetVariableDescriptorCountAllocateInfoEXT',['../struct_vk_descriptor_set_variable_descriptor_count_allocate_info_e_x_t.html',1,'']]],
  ['vkdescriptorsetvariabledescriptorcountlayoutsupportext_134',['VkDescriptorSetVariableDescriptorCountLayoutSupportEXT',['../struct_vk_descriptor_set_variable_descriptor_count_layout_support_e_x_t.html',1,'']]],
  ['vkdescriptorupdatetemplatecreateinfo_135',['VkDescriptorUpdateTemplateCreateInfo',['../struct_vk_descriptor_update_template_create_info.html',1,'']]],
  ['vkdescriptorupdatetemplateentry_136',['VkDescriptorUpdateTemplateEntry',['../struct_vk_descriptor_update_template_entry.html',1,'']]],
  ['vkdevicecreateinfo_137',['VkDeviceCreateInfo',['../struct_vk_device_create_info.html',1,'']]],
  ['vkdeviceeventinfoext_138',['VkDeviceEventInfoEXT',['../struct_vk_device_event_info_e_x_t.html',1,'']]],
  ['vkdevicegeneratedcommandsfeaturesnvx_139',['VkDeviceGeneratedCommandsFeaturesNVX',['../struct_vk_device_generated_commands_features_n_v_x.html',1,'']]],
  ['vkdevicegeneratedcommandslimitsnvx_140',['VkDeviceGeneratedCommandsLimitsNVX',['../struct_vk_device_generated_commands_limits_n_v_x.html',1,'']]],
  ['vkdevicegroupbindsparseinfo_141',['VkDeviceGroupBindSparseInfo',['../struct_vk_device_group_bind_sparse_info.html',1,'']]],
  ['vkdevicegroupcommandbufferbegininfo_142',['VkDeviceGroupCommandBufferBeginInfo',['../struct_vk_device_group_command_buffer_begin_info.html',1,'']]],
  ['vkdevicegroupdevicecreateinfo_143',['VkDeviceGroupDeviceCreateInfo',['../struct_vk_device_group_device_create_info.html',1,'']]],
  ['vkdevicegrouppresentcapabilitieskhr_144',['VkDeviceGroupPresentCapabilitiesKHR',['../struct_vk_device_group_present_capabilities_k_h_r.html',1,'']]],
  ['vkdevicegrouppresentinfokhr_145',['VkDeviceGroupPresentInfoKHR',['../struct_vk_device_group_present_info_k_h_r.html',1,'']]],
  ['vkdevicegrouprenderpassbegininfo_146',['VkDeviceGroupRenderPassBeginInfo',['../struct_vk_device_group_render_pass_begin_info.html',1,'']]],
  ['vkdevicegroupsubmitinfo_147',['VkDeviceGroupSubmitInfo',['../struct_vk_device_group_submit_info.html',1,'']]],
  ['vkdevicegroupswapchaincreateinfokhr_148',['VkDeviceGroupSwapchainCreateInfoKHR',['../struct_vk_device_group_swapchain_create_info_k_h_r.html',1,'']]],
  ['vkdevicequeuecreateinfo_149',['VkDeviceQueueCreateInfo',['../struct_vk_device_queue_create_info.html',1,'']]],
  ['vkdevicequeueglobalprioritycreateinfoext_150',['VkDeviceQueueGlobalPriorityCreateInfoEXT',['../struct_vk_device_queue_global_priority_create_info_e_x_t.html',1,'']]],
  ['vkdevicequeueinfo2_151',['VkDeviceQueueInfo2',['../struct_vk_device_queue_info2.html',1,'']]],
  ['vkdispatchindirectcommand_152',['VkDispatchIndirectCommand',['../struct_vk_dispatch_indirect_command.html',1,'']]],
  ['vkdisplayeventinfoext_153',['VkDisplayEventInfoEXT',['../struct_vk_display_event_info_e_x_t.html',1,'']]],
  ['vkdisplaymodecreateinfokhr_154',['VkDisplayModeCreateInfoKHR',['../struct_vk_display_mode_create_info_k_h_r.html',1,'']]],
  ['vkdisplaymodeparameterskhr_155',['VkDisplayModeParametersKHR',['../struct_vk_display_mode_parameters_k_h_r.html',1,'']]],
  ['vkdisplaymodeproperties2khr_156',['VkDisplayModeProperties2KHR',['../struct_vk_display_mode_properties2_k_h_r.html',1,'']]],
  ['vkdisplaymodepropertieskhr_157',['VkDisplayModePropertiesKHR',['../struct_vk_display_mode_properties_k_h_r.html',1,'']]],
  ['vkdisplayplanecapabilities2khr_158',['VkDisplayPlaneCapabilities2KHR',['../struct_vk_display_plane_capabilities2_k_h_r.html',1,'']]],
  ['vkdisplayplanecapabilitieskhr_159',['VkDisplayPlaneCapabilitiesKHR',['../struct_vk_display_plane_capabilities_k_h_r.html',1,'']]],
  ['vkdisplayplaneinfo2khr_160',['VkDisplayPlaneInfo2KHR',['../struct_vk_display_plane_info2_k_h_r.html',1,'']]],
  ['vkdisplayplaneproperties2khr_161',['VkDisplayPlaneProperties2KHR',['../struct_vk_display_plane_properties2_k_h_r.html',1,'']]],
  ['vkdisplayplanepropertieskhr_162',['VkDisplayPlanePropertiesKHR',['../struct_vk_display_plane_properties_k_h_r.html',1,'']]],
  ['vkdisplaypowerinfoext_163',['VkDisplayPowerInfoEXT',['../struct_vk_display_power_info_e_x_t.html',1,'']]],
  ['vkdisplaypresentinfokhr_164',['VkDisplayPresentInfoKHR',['../struct_vk_display_present_info_k_h_r.html',1,'']]],
  ['vkdisplayproperties2khr_165',['VkDisplayProperties2KHR',['../struct_vk_display_properties2_k_h_r.html',1,'']]],
  ['vkdisplaypropertieskhr_166',['VkDisplayPropertiesKHR',['../struct_vk_display_properties_k_h_r.html',1,'']]],
  ['vkdisplaysurfacecreateinfokhr_167',['VkDisplaySurfaceCreateInfoKHR',['../struct_vk_display_surface_create_info_k_h_r.html',1,'']]],
  ['vkdrawindexedindirectcommand_168',['VkDrawIndexedIndirectCommand',['../struct_vk_draw_indexed_indirect_command.html',1,'']]],
  ['vkdrawindirectcommand_169',['VkDrawIndirectCommand',['../struct_vk_draw_indirect_command.html',1,'']]],
  ['vkenumerateinstanceextensionpropertieschain_170',['VkEnumerateInstanceExtensionPropertiesChain',['../struct_vk_enumerate_instance_extension_properties_chain.html',1,'']]],
  ['vkenumerateinstancelayerpropertieschain_171',['VkEnumerateInstanceLayerPropertiesChain',['../struct_vk_enumerate_instance_layer_properties_chain.html',1,'']]],
  ['vkenumerateinstanceversionchain_172',['VkEnumerateInstanceVersionChain',['../struct_vk_enumerate_instance_version_chain.html',1,'']]],
  ['vkeventcreateinfo_173',['VkEventCreateInfo',['../struct_vk_event_create_info.html',1,'']]],
  ['vkexportfencecreateinfo_174',['VkExportFenceCreateInfo',['../struct_vk_export_fence_create_info.html',1,'']]],
  ['vkexportfencewin32handleinfokhr_175',['VkExportFenceWin32HandleInfoKHR',['../struct_vk_export_fence_win32_handle_info_k_h_r.html',1,'']]],
  ['vkexportmemoryallocateinfo_176',['VkExportMemoryAllocateInfo',['../struct_vk_export_memory_allocate_info.html',1,'']]],
  ['vkexportmemoryallocateinfonv_177',['VkExportMemoryAllocateInfoNV',['../struct_vk_export_memory_allocate_info_n_v.html',1,'']]],
  ['vkexportmemorywin32handleinfokhr_178',['VkExportMemoryWin32HandleInfoKHR',['../struct_vk_export_memory_win32_handle_info_k_h_r.html',1,'']]],
  ['vkexportmemorywin32handleinfonv_179',['VkExportMemoryWin32HandleInfoNV',['../struct_vk_export_memory_win32_handle_info_n_v.html',1,'']]],
  ['vkexportsemaphorecreateinfo_180',['VkExportSemaphoreCreateInfo',['../struct_vk_export_semaphore_create_info.html',1,'']]],
  ['vkexportsemaphorewin32handleinfokhr_181',['VkExportSemaphoreWin32HandleInfoKHR',['../struct_vk_export_semaphore_win32_handle_info_k_h_r.html',1,'']]],
  ['vkextensionproperties_182',['VkExtensionProperties',['../struct_vk_extension_properties.html',1,'']]],
  ['vkextent2d_183',['VkExtent2D',['../struct_vk_extent2_d.html',1,'']]],
  ['vkextent3d_184',['VkExtent3D',['../struct_vk_extent3_d.html',1,'']]],
  ['vkexternalbufferproperties_185',['VkExternalBufferProperties',['../struct_vk_external_buffer_properties.html',1,'']]],
  ['vkexternalfenceproperties_186',['VkExternalFenceProperties',['../struct_vk_external_fence_properties.html',1,'']]],
  ['vkexternalformatandroid_187',['VkExternalFormatANDROID',['../struct_vk_external_format_a_n_d_r_o_i_d.html',1,'']]],
  ['vkexternalimageformatproperties_188',['VkExternalImageFormatProperties',['../struct_vk_external_image_format_properties.html',1,'']]],
  ['vkexternalimageformatpropertiesnv_189',['VkExternalImageFormatPropertiesNV',['../struct_vk_external_image_format_properties_n_v.html',1,'']]],
  ['vkexternalmemorybuffercreateinfo_190',['VkExternalMemoryBufferCreateInfo',['../struct_vk_external_memory_buffer_create_info.html',1,'']]],
  ['vkexternalmemoryimagecreateinfo_191',['VkExternalMemoryImageCreateInfo',['../struct_vk_external_memory_image_create_info.html',1,'']]],
  ['vkexternalmemoryimagecreateinfonv_192',['VkExternalMemoryImageCreateInfoNV',['../struct_vk_external_memory_image_create_info_n_v.html',1,'']]],
  ['vkexternalmemoryproperties_193',['VkExternalMemoryProperties',['../struct_vk_external_memory_properties.html',1,'']]],
  ['vkexternalsemaphoreproperties_194',['VkExternalSemaphoreProperties',['../struct_vk_external_semaphore_properties.html',1,'']]],
  ['vkfencecreateinfo_195',['VkFenceCreateInfo',['../struct_vk_fence_create_info.html',1,'']]],
  ['vkfencegetfdinfokhr_196',['VkFenceGetFdInfoKHR',['../struct_vk_fence_get_fd_info_k_h_r.html',1,'']]],
  ['vkfencegetwin32handleinfokhr_197',['VkFenceGetWin32HandleInfoKHR',['../struct_vk_fence_get_win32_handle_info_k_h_r.html',1,'']]],
  ['vkformatproperties_198',['VkFormatProperties',['../struct_vk_format_properties.html',1,'']]],
  ['vkformatproperties2_199',['VkFormatProperties2',['../struct_vk_format_properties2.html',1,'']]],
  ['vkframebuffercreateinfo_200',['VkFramebufferCreateInfo',['../struct_vk_framebuffer_create_info.html',1,'']]],
  ['vkgraphicspipelinecreateinfo_201',['VkGraphicsPipelineCreateInfo',['../struct_vk_graphics_pipeline_create_info.html',1,'']]],
  ['vkhdrmetadataext_202',['VkHdrMetadataEXT',['../struct_vk_hdr_metadata_e_x_t.html',1,'']]],
  ['vkicdsurfacebase_203',['VkIcdSurfaceBase',['../struct_vk_icd_surface_base.html',1,'']]],
  ['vkicdsurfacedisplay_204',['VkIcdSurfaceDisplay',['../struct_vk_icd_surface_display.html',1,'']]],
  ['vkimageblit_205',['VkImageBlit',['../struct_vk_image_blit.html',1,'']]],
  ['vkimagecopy_206',['VkImageCopy',['../struct_vk_image_copy.html',1,'']]],
  ['vkimagecreateinfo_207',['VkImageCreateInfo',['../struct_vk_image_create_info.html',1,'']]],
  ['vkimageformatlistcreateinfokhr_208',['VkImageFormatListCreateInfoKHR',['../struct_vk_image_format_list_create_info_k_h_r.html',1,'']]],
  ['vkimageformatproperties_209',['VkImageFormatProperties',['../struct_vk_image_format_properties.html',1,'']]],
  ['vkimageformatproperties2_210',['VkImageFormatProperties2',['../struct_vk_image_format_properties2.html',1,'']]],
  ['vkimagememorybarrier_211',['VkImageMemoryBarrier',['../struct_vk_image_memory_barrier.html',1,'']]],
  ['vkimagememoryrequirementsinfo2_212',['VkImageMemoryRequirementsInfo2',['../struct_vk_image_memory_requirements_info2.html',1,'']]],
  ['vkimageplanememoryrequirementsinfo_213',['VkImagePlaneMemoryRequirementsInfo',['../struct_vk_image_plane_memory_requirements_info.html',1,'']]],
  ['vkimageresolve_214',['VkImageResolve',['../struct_vk_image_resolve.html',1,'']]],
  ['vkimagesparsememoryrequirementsinfo2_215',['VkImageSparseMemoryRequirementsInfo2',['../struct_vk_image_sparse_memory_requirements_info2.html',1,'']]],
  ['vkimagesubresource_216',['VkImageSubresource',['../struct_vk_image_subresource.html',1,'']]],
  ['vkimagesubresourcelayers_217',['VkImageSubresourceLayers',['../struct_vk_image_subresource_layers.html',1,'']]],
  ['vkimagesubresourcerange_218',['VkImageSubresourceRange',['../struct_vk_image_subresource_range.html',1,'']]],
  ['vkimageswapchaincreateinfokhr_219',['VkImageSwapchainCreateInfoKHR',['../struct_vk_image_swapchain_create_info_k_h_r.html',1,'']]],
  ['vkimageviewcreateinfo_220',['VkImageViewCreateInfo',['../struct_vk_image_view_create_info.html',1,'']]],
  ['vkimageviewusagecreateinfo_221',['VkImageViewUsageCreateInfo',['../struct_vk_image_view_usage_create_info.html',1,'']]],
  ['vkimportandroidhardwarebufferinfoandroid_222',['VkImportAndroidHardwareBufferInfoANDROID',['../struct_vk_import_android_hardware_buffer_info_a_n_d_r_o_i_d.html',1,'']]],
  ['vkimportfencefdinfokhr_223',['VkImportFenceFdInfoKHR',['../struct_vk_import_fence_fd_info_k_h_r.html',1,'']]],
  ['vkimportfencewin32handleinfokhr_224',['VkImportFenceWin32HandleInfoKHR',['../struct_vk_import_fence_win32_handle_info_k_h_r.html',1,'']]],
  ['vkimportmemoryfdinfokhr_225',['VkImportMemoryFdInfoKHR',['../struct_vk_import_memory_fd_info_k_h_r.html',1,'']]],
  ['vkimportmemoryhostpointerinfoext_226',['VkImportMemoryHostPointerInfoEXT',['../struct_vk_import_memory_host_pointer_info_e_x_t.html',1,'']]],
  ['vkimportmemorywin32handleinfokhr_227',['VkImportMemoryWin32HandleInfoKHR',['../struct_vk_import_memory_win32_handle_info_k_h_r.html',1,'']]],
  ['vkimportmemorywin32handleinfonv_228',['VkImportMemoryWin32HandleInfoNV',['../struct_vk_import_memory_win32_handle_info_n_v.html',1,'']]],
  ['vkimportsemaphorefdinfokhr_229',['VkImportSemaphoreFdInfoKHR',['../struct_vk_import_semaphore_fd_info_k_h_r.html',1,'']]],
  ['vkimportsemaphorewin32handleinfokhr_230',['VkImportSemaphoreWin32HandleInfoKHR',['../struct_vk_import_semaphore_win32_handle_info_k_h_r.html',1,'']]],
  ['vkindirectcommandslayoutcreateinfonvx_231',['VkIndirectCommandsLayoutCreateInfoNVX',['../struct_vk_indirect_commands_layout_create_info_n_v_x.html',1,'']]],
  ['vkindirectcommandslayouttokennvx_232',['VkIndirectCommandsLayoutTokenNVX',['../struct_vk_indirect_commands_layout_token_n_v_x.html',1,'']]],
  ['vkindirectcommandstokennvx_233',['VkIndirectCommandsTokenNVX',['../struct_vk_indirect_commands_token_n_v_x.html',1,'']]],
  ['vkinputattachmentaspectreference_234',['VkInputAttachmentAspectReference',['../struct_vk_input_attachment_aspect_reference.html',1,'']]],
  ['vkinstancecreateinfo_235',['VkInstanceCreateInfo',['../struct_vk_instance_create_info.html',1,'']]],
  ['vkiossurfacecreateinfomvk_236',['VkIOSSurfaceCreateInfoMVK',['../struct_vk_i_o_s_surface_create_info_m_v_k.html',1,'']]],
  ['vklayerdevicecreateinfo_237',['VkLayerDeviceCreateInfo',['../struct_vk_layer_device_create_info.html',1,'']]],
  ['vklayerdeviceinfo_5f_238',['VkLayerDeviceInfo_',['../struct_vk_layer_device_info__.html',1,'']]],
  ['vklayerdevicelink_5f_239',['VkLayerDeviceLink_',['../struct_vk_layer_device_link__.html',1,'']]],
  ['vklayerinstancecreateinfo_240',['VkLayerInstanceCreateInfo',['../struct_vk_layer_instance_create_info.html',1,'']]],
  ['vklayerinstancelink_5f_241',['VkLayerInstanceLink_',['../struct_vk_layer_instance_link__.html',1,'']]],
  ['vklayerproperties_242',['VkLayerProperties',['../struct_vk_layer_properties.html',1,'']]],
  ['vkmacossurfacecreateinfomvk_243',['VkMacOSSurfaceCreateInfoMVK',['../struct_vk_mac_o_s_surface_create_info_m_v_k.html',1,'']]],
  ['vkmappedmemoryrange_244',['VkMappedMemoryRange',['../struct_vk_mapped_memory_range.html',1,'']]],
  ['vkmemoryallocateflagsinfo_245',['VkMemoryAllocateFlagsInfo',['../struct_vk_memory_allocate_flags_info.html',1,'']]],
  ['vkmemoryallocateinfo_246',['VkMemoryAllocateInfo',['../struct_vk_memory_allocate_info.html',1,'']]],
  ['vkmemorybarrier_247',['VkMemoryBarrier',['../struct_vk_memory_barrier.html',1,'']]],
  ['vkmemorydedicatedallocateinfo_248',['VkMemoryDedicatedAllocateInfo',['../struct_vk_memory_dedicated_allocate_info.html',1,'']]],
  ['vkmemorydedicatedrequirements_249',['VkMemoryDedicatedRequirements',['../struct_vk_memory_dedicated_requirements.html',1,'']]],
  ['vkmemoryfdpropertieskhr_250',['VkMemoryFdPropertiesKHR',['../struct_vk_memory_fd_properties_k_h_r.html',1,'']]],
  ['vkmemorygetandroidhardwarebufferinfoandroid_251',['VkMemoryGetAndroidHardwareBufferInfoANDROID',['../struct_vk_memory_get_android_hardware_buffer_info_a_n_d_r_o_i_d.html',1,'']]],
  ['vkmemorygetfdinfokhr_252',['VkMemoryGetFdInfoKHR',['../struct_vk_memory_get_fd_info_k_h_r.html',1,'']]],
  ['vkmemorygetwin32handleinfokhr_253',['VkMemoryGetWin32HandleInfoKHR',['../struct_vk_memory_get_win32_handle_info_k_h_r.html',1,'']]],
  ['vkmemoryheap_254',['VkMemoryHeap',['../struct_vk_memory_heap.html',1,'']]],
  ['vkmemoryhostpointerpropertiesext_255',['VkMemoryHostPointerPropertiesEXT',['../struct_vk_memory_host_pointer_properties_e_x_t.html',1,'']]],
  ['vkmemoryrequirements_256',['VkMemoryRequirements',['../struct_vk_memory_requirements.html',1,'']]],
  ['vkmemoryrequirements2_257',['VkMemoryRequirements2',['../struct_vk_memory_requirements2.html',1,'']]],
  ['vkmemorytype_258',['VkMemoryType',['../struct_vk_memory_type.html',1,'']]],
  ['vkmemorywin32handlepropertieskhr_259',['VkMemoryWin32HandlePropertiesKHR',['../struct_vk_memory_win32_handle_properties_k_h_r.html',1,'']]],
  ['vkmirsurfacecreateinfokhr_260',['VkMirSurfaceCreateInfoKHR',['../struct_vk_mir_surface_create_info_k_h_r.html',1,'']]],
  ['vkmultisamplepropertiesext_261',['VkMultisamplePropertiesEXT',['../struct_vk_multisample_properties_e_x_t.html',1,'']]],
  ['vknegotiatelayerinterface_262',['VkNegotiateLayerInterface',['../struct_vk_negotiate_layer_interface.html',1,'']]],
  ['vkobjecttablecreateinfonvx_263',['VkObjectTableCreateInfoNVX',['../struct_vk_object_table_create_info_n_v_x.html',1,'']]],
  ['vkobjecttabledescriptorsetentrynvx_264',['VkObjectTableDescriptorSetEntryNVX',['../struct_vk_object_table_descriptor_set_entry_n_v_x.html',1,'']]],
  ['vkobjecttableentrynvx_265',['VkObjectTableEntryNVX',['../struct_vk_object_table_entry_n_v_x.html',1,'']]],
  ['vkobjecttableindexbufferentrynvx_266',['VkObjectTableIndexBufferEntryNVX',['../struct_vk_object_table_index_buffer_entry_n_v_x.html',1,'']]],
  ['vkobjecttablepipelineentrynvx_267',['VkObjectTablePipelineEntryNVX',['../struct_vk_object_table_pipeline_entry_n_v_x.html',1,'']]],
  ['vkobjecttablepushconstantentrynvx_268',['VkObjectTablePushConstantEntryNVX',['../struct_vk_object_table_push_constant_entry_n_v_x.html',1,'']]],
  ['vkobjecttablevertexbufferentrynvx_269',['VkObjectTableVertexBufferEntryNVX',['../struct_vk_object_table_vertex_buffer_entry_n_v_x.html',1,'']]],
  ['vkoffset2d_270',['VkOffset2D',['../struct_vk_offset2_d.html',1,'']]],
  ['vkoffset3d_271',['VkOffset3D',['../struct_vk_offset3_d.html',1,'']]],
  ['vkpastpresentationtiminggoogle_272',['VkPastPresentationTimingGOOGLE',['../struct_vk_past_presentation_timing_g_o_o_g_l_e.html',1,'']]],
  ['vkphysicaldevice16bitstoragefeatures_273',['VkPhysicalDevice16BitStorageFeatures',['../struct_vk_physical_device16_bit_storage_features.html',1,'']]],
  ['vkphysicaldevice8bitstoragefeatureskhr_274',['VkPhysicalDevice8BitStorageFeaturesKHR',['../struct_vk_physical_device8_bit_storage_features_k_h_r.html',1,'']]],
  ['vkphysicaldeviceblendoperationadvancedfeaturesext_275',['VkPhysicalDeviceBlendOperationAdvancedFeaturesEXT',['../struct_vk_physical_device_blend_operation_advanced_features_e_x_t.html',1,'']]],
  ['vkphysicaldeviceblendoperationadvancedpropertiesext_276',['VkPhysicalDeviceBlendOperationAdvancedPropertiesEXT',['../struct_vk_physical_device_blend_operation_advanced_properties_e_x_t.html',1,'']]],
  ['vkphysicaldeviceconditionalrenderingfeaturesext_277',['VkPhysicalDeviceConditionalRenderingFeaturesEXT',['../struct_vk_physical_device_conditional_rendering_features_e_x_t.html',1,'']]],
  ['vkphysicaldeviceconservativerasterizationpropertiesext_278',['VkPhysicalDeviceConservativeRasterizationPropertiesEXT',['../struct_vk_physical_device_conservative_rasterization_properties_e_x_t.html',1,'']]],
  ['vkphysicaldevicedescriptorindexingfeaturesext_279',['VkPhysicalDeviceDescriptorIndexingFeaturesEXT',['../struct_vk_physical_device_descriptor_indexing_features_e_x_t.html',1,'']]],
  ['vkphysicaldevicedescriptorindexingpropertiesext_280',['VkPhysicalDeviceDescriptorIndexingPropertiesEXT',['../struct_vk_physical_device_descriptor_indexing_properties_e_x_t.html',1,'']]],
  ['vkphysicaldevicediscardrectanglepropertiesext_281',['VkPhysicalDeviceDiscardRectanglePropertiesEXT',['../struct_vk_physical_device_discard_rectangle_properties_e_x_t.html',1,'']]],
  ['vkphysicaldeviceexternalbufferinfo_282',['VkPhysicalDeviceExternalBufferInfo',['../struct_vk_physical_device_external_buffer_info.html',1,'']]],
  ['vkphysicaldeviceexternalfenceinfo_283',['VkPhysicalDeviceExternalFenceInfo',['../struct_vk_physical_device_external_fence_info.html',1,'']]],
  ['vkphysicaldeviceexternalimageformatinfo_284',['VkPhysicalDeviceExternalImageFormatInfo',['../struct_vk_physical_device_external_image_format_info.html',1,'']]],
  ['vkphysicaldeviceexternalmemoryhostpropertiesext_285',['VkPhysicalDeviceExternalMemoryHostPropertiesEXT',['../struct_vk_physical_device_external_memory_host_properties_e_x_t.html',1,'']]],
  ['vkphysicaldeviceexternalsemaphoreinfo_286',['VkPhysicalDeviceExternalSemaphoreInfo',['../struct_vk_physical_device_external_semaphore_info.html',1,'']]],
  ['vkphysicaldevicefeatures_287',['VkPhysicalDeviceFeatures',['../struct_vk_physical_device_features.html',1,'']]],
  ['vkphysicaldevicefeatures2_288',['VkPhysicalDeviceFeatures2',['../struct_vk_physical_device_features2.html',1,'']]],
  ['vkphysicaldevicegroupproperties_289',['VkPhysicalDeviceGroupProperties',['../struct_vk_physical_device_group_properties.html',1,'']]],
  ['vkphysicaldeviceidproperties_290',['VkPhysicalDeviceIDProperties',['../struct_vk_physical_device_i_d_properties.html',1,'']]],
  ['vkphysicaldeviceimageformatinfo2_291',['VkPhysicalDeviceImageFormatInfo2',['../struct_vk_physical_device_image_format_info2.html',1,'']]],
  ['vkphysicaldevicelimits_292',['VkPhysicalDeviceLimits',['../struct_vk_physical_device_limits.html',1,'']]],
  ['vkphysicaldevicemaintenance3properties_293',['VkPhysicalDeviceMaintenance3Properties',['../struct_vk_physical_device_maintenance3_properties.html',1,'']]],
  ['vkphysicaldevicememoryproperties_294',['VkPhysicalDeviceMemoryProperties',['../struct_vk_physical_device_memory_properties.html',1,'']]],
  ['vkphysicaldevicememoryproperties2_295',['VkPhysicalDeviceMemoryProperties2',['../struct_vk_physical_device_memory_properties2.html',1,'']]],
  ['vkphysicaldevicemultiviewfeatures_296',['VkPhysicalDeviceMultiviewFeatures',['../struct_vk_physical_device_multiview_features.html',1,'']]],
  ['vkphysicaldevicemultiviewperviewattributespropertiesnvx_297',['VkPhysicalDeviceMultiviewPerViewAttributesPropertiesNVX',['../struct_vk_physical_device_multiview_per_view_attributes_properties_n_v_x.html',1,'']]],
  ['vkphysicaldevicemultiviewproperties_298',['VkPhysicalDeviceMultiviewProperties',['../struct_vk_physical_device_multiview_properties.html',1,'']]],
  ['vkphysicaldevicepointclippingproperties_299',['VkPhysicalDevicePointClippingProperties',['../struct_vk_physical_device_point_clipping_properties.html',1,'']]],
  ['vkphysicaldeviceproperties_300',['VkPhysicalDeviceProperties',['../struct_vk_physical_device_properties.html',1,'']]],
  ['vkphysicaldeviceproperties2_301',['VkPhysicalDeviceProperties2',['../struct_vk_physical_device_properties2.html',1,'']]],
  ['vkphysicaldeviceprotectedmemoryfeatures_302',['VkPhysicalDeviceProtectedMemoryFeatures',['../struct_vk_physical_device_protected_memory_features.html',1,'']]],
  ['vkphysicaldeviceprotectedmemoryproperties_303',['VkPhysicalDeviceProtectedMemoryProperties',['../struct_vk_physical_device_protected_memory_properties.html',1,'']]],
  ['vkphysicaldevicepushdescriptorpropertieskhr_304',['VkPhysicalDevicePushDescriptorPropertiesKHR',['../struct_vk_physical_device_push_descriptor_properties_k_h_r.html',1,'']]],
  ['vkphysicaldevicesamplelocationspropertiesext_305',['VkPhysicalDeviceSampleLocationsPropertiesEXT',['../struct_vk_physical_device_sample_locations_properties_e_x_t.html',1,'']]],
  ['vkphysicaldevicesamplerfilterminmaxpropertiesext_306',['VkPhysicalDeviceSamplerFilterMinmaxPropertiesEXT',['../struct_vk_physical_device_sampler_filter_minmax_properties_e_x_t.html',1,'']]],
  ['vkphysicaldevicesamplerycbcrconversionfeatures_307',['VkPhysicalDeviceSamplerYcbcrConversionFeatures',['../struct_vk_physical_device_sampler_ycbcr_conversion_features.html',1,'']]],
  ['vkphysicaldeviceshadercorepropertiesamd_308',['VkPhysicalDeviceShaderCorePropertiesAMD',['../struct_vk_physical_device_shader_core_properties_a_m_d.html',1,'']]],
  ['vkphysicaldeviceshaderdrawparameterfeatures_309',['VkPhysicalDeviceShaderDrawParameterFeatures',['../struct_vk_physical_device_shader_draw_parameter_features.html',1,'']]],
  ['vkphysicaldevicesparseimageformatinfo2_310',['VkPhysicalDeviceSparseImageFormatInfo2',['../struct_vk_physical_device_sparse_image_format_info2.html',1,'']]],
  ['vkphysicaldevicesparseproperties_311',['VkPhysicalDeviceSparseProperties',['../struct_vk_physical_device_sparse_properties.html',1,'']]],
  ['vkphysicaldevicesubgroupproperties_312',['VkPhysicalDeviceSubgroupProperties',['../struct_vk_physical_device_subgroup_properties.html',1,'']]],
  ['vkphysicaldevicesurfaceinfo2khr_313',['VkPhysicalDeviceSurfaceInfo2KHR',['../struct_vk_physical_device_surface_info2_k_h_r.html',1,'']]],
  ['vkphysicaldevicevariablepointerfeatures_314',['VkPhysicalDeviceVariablePointerFeatures',['../struct_vk_physical_device_variable_pointer_features.html',1,'']]],
  ['vkphysicaldevicevertexattributedivisorpropertiesext_315',['VkPhysicalDeviceVertexAttributeDivisorPropertiesEXT',['../struct_vk_physical_device_vertex_attribute_divisor_properties_e_x_t.html',1,'']]],
  ['vkpipelinecachecreateinfo_316',['VkPipelineCacheCreateInfo',['../struct_vk_pipeline_cache_create_info.html',1,'']]],
  ['vkpipelinecolorblendadvancedstatecreateinfoext_317',['VkPipelineColorBlendAdvancedStateCreateInfoEXT',['../struct_vk_pipeline_color_blend_advanced_state_create_info_e_x_t.html',1,'']]],
  ['vkpipelinecolorblendattachmentstate_318',['VkPipelineColorBlendAttachmentState',['../struct_vk_pipeline_color_blend_attachment_state.html',1,'']]],
  ['vkpipelinecolorblendstatecreateinfo_319',['VkPipelineColorBlendStateCreateInfo',['../struct_vk_pipeline_color_blend_state_create_info.html',1,'']]],
  ['vkpipelinecoveragemodulationstatecreateinfonv_320',['VkPipelineCoverageModulationStateCreateInfoNV',['../struct_vk_pipeline_coverage_modulation_state_create_info_n_v.html',1,'']]],
  ['vkpipelinecoveragetocolorstatecreateinfonv_321',['VkPipelineCoverageToColorStateCreateInfoNV',['../struct_vk_pipeline_coverage_to_color_state_create_info_n_v.html',1,'']]],
  ['vkpipelinedepthstencilstatecreateinfo_322',['VkPipelineDepthStencilStateCreateInfo',['../struct_vk_pipeline_depth_stencil_state_create_info.html',1,'']]],
  ['vkpipelinediscardrectanglestatecreateinfoext_323',['VkPipelineDiscardRectangleStateCreateInfoEXT',['../struct_vk_pipeline_discard_rectangle_state_create_info_e_x_t.html',1,'']]],
  ['vkpipelinedynamicstatecreateinfo_324',['VkPipelineDynamicStateCreateInfo',['../struct_vk_pipeline_dynamic_state_create_info.html',1,'']]],
  ['vkpipelineinputassemblystatecreateinfo_325',['VkPipelineInputAssemblyStateCreateInfo',['../struct_vk_pipeline_input_assembly_state_create_info.html',1,'']]],
  ['vkpipelinelayoutcreateinfo_326',['VkPipelineLayoutCreateInfo',['../struct_vk_pipeline_layout_create_info.html',1,'']]],
  ['vkpipelinemultisamplestatecreateinfo_327',['VkPipelineMultisampleStateCreateInfo',['../struct_vk_pipeline_multisample_state_create_info.html',1,'']]],
  ['vkpipelinerasterizationconservativestatecreateinfoext_328',['VkPipelineRasterizationConservativeStateCreateInfoEXT',['../struct_vk_pipeline_rasterization_conservative_state_create_info_e_x_t.html',1,'']]],
  ['vkpipelinerasterizationstatecreateinfo_329',['VkPipelineRasterizationStateCreateInfo',['../struct_vk_pipeline_rasterization_state_create_info.html',1,'']]],
  ['vkpipelinerasterizationstaterasterizationorderamd_330',['VkPipelineRasterizationStateRasterizationOrderAMD',['../struct_vk_pipeline_rasterization_state_rasterization_order_a_m_d.html',1,'']]],
  ['vkpipelinesamplelocationsstatecreateinfoext_331',['VkPipelineSampleLocationsStateCreateInfoEXT',['../struct_vk_pipeline_sample_locations_state_create_info_e_x_t.html',1,'']]],
  ['vkpipelineshaderstagecreateinfo_332',['VkPipelineShaderStageCreateInfo',['../struct_vk_pipeline_shader_stage_create_info.html',1,'']]],
  ['vkpipelinetessellationdomainoriginstatecreateinfo_333',['VkPipelineTessellationDomainOriginStateCreateInfo',['../struct_vk_pipeline_tessellation_domain_origin_state_create_info.html',1,'']]],
  ['vkpipelinetessellationstatecreateinfo_334',['VkPipelineTessellationStateCreateInfo',['../struct_vk_pipeline_tessellation_state_create_info.html',1,'']]],
  ['vkpipelinevertexinputdivisorstatecreateinfoext_335',['VkPipelineVertexInputDivisorStateCreateInfoEXT',['../struct_vk_pipeline_vertex_input_divisor_state_create_info_e_x_t.html',1,'']]],
  ['vkpipelinevertexinputstatecreateinfo_336',['VkPipelineVertexInputStateCreateInfo',['../struct_vk_pipeline_vertex_input_state_create_info.html',1,'']]],
  ['vkpipelineviewportstatecreateinfo_337',['VkPipelineViewportStateCreateInfo',['../struct_vk_pipeline_viewport_state_create_info.html',1,'']]],
  ['vkpipelineviewportswizzlestatecreateinfonv_338',['VkPipelineViewportSwizzleStateCreateInfoNV',['../struct_vk_pipeline_viewport_swizzle_state_create_info_n_v.html',1,'']]],
  ['vkpipelineviewportwscalingstatecreateinfonv_339',['VkPipelineViewportWScalingStateCreateInfoNV',['../struct_vk_pipeline_viewport_w_scaling_state_create_info_n_v.html',1,'']]],
  ['vkpresentinfokhr_340',['VkPresentInfoKHR',['../struct_vk_present_info_k_h_r.html',1,'']]],
  ['vkpresentregionkhr_341',['VkPresentRegionKHR',['../struct_vk_present_region_k_h_r.html',1,'']]],
  ['vkpresentregionskhr_342',['VkPresentRegionsKHR',['../struct_vk_present_regions_k_h_r.html',1,'']]],
  ['vkpresenttimegoogle_343',['VkPresentTimeGOOGLE',['../struct_vk_present_time_g_o_o_g_l_e.html',1,'']]],
  ['vkpresenttimesinfogoogle_344',['VkPresentTimesInfoGOOGLE',['../struct_vk_present_times_info_g_o_o_g_l_e.html',1,'']]],
  ['vkprotectedsubmitinfo_345',['VkProtectedSubmitInfo',['../struct_vk_protected_submit_info.html',1,'']]],
  ['vkpushconstantrange_346',['VkPushConstantRange',['../struct_vk_push_constant_range.html',1,'']]],
  ['vkquerypoolcreateinfo_347',['VkQueryPoolCreateInfo',['../struct_vk_query_pool_create_info.html',1,'']]],
  ['vkqueuefamilycheckpointpropertiesnv_348',['VkQueueFamilyCheckpointPropertiesNV',['../struct_vk_queue_family_checkpoint_properties_n_v.html',1,'']]],
  ['vkqueuefamilyproperties_349',['VkQueueFamilyProperties',['../struct_vk_queue_family_properties.html',1,'']]],
  ['vkqueuefamilyproperties2_350',['VkQueueFamilyProperties2',['../struct_vk_queue_family_properties2.html',1,'']]],
  ['vkrect2d_351',['VkRect2D',['../struct_vk_rect2_d.html',1,'']]],
  ['vkrectlayerkhr_352',['VkRectLayerKHR',['../struct_vk_rect_layer_k_h_r.html',1,'']]],
  ['vkrefreshcycledurationgoogle_353',['VkRefreshCycleDurationGOOGLE',['../struct_vk_refresh_cycle_duration_g_o_o_g_l_e.html',1,'']]],
  ['vkrenderpassbegininfo_354',['VkRenderPassBeginInfo',['../struct_vk_render_pass_begin_info.html',1,'']]],
  ['vkrenderpasscreateinfo_355',['VkRenderPassCreateInfo',['../struct_vk_render_pass_create_info.html',1,'']]],
  ['vkrenderpasscreateinfo2khr_356',['VkRenderPassCreateInfo2KHR',['../struct_vk_render_pass_create_info2_k_h_r.html',1,'']]],
  ['vkrenderpassinputattachmentaspectcreateinfo_357',['VkRenderPassInputAttachmentAspectCreateInfo',['../struct_vk_render_pass_input_attachment_aspect_create_info.html',1,'']]],
  ['vkrenderpassmultiviewcreateinfo_358',['VkRenderPassMultiviewCreateInfo',['../struct_vk_render_pass_multiview_create_info.html',1,'']]],
  ['vkrenderpasssamplelocationsbegininfoext_359',['VkRenderPassSampleLocationsBeginInfoEXT',['../struct_vk_render_pass_sample_locations_begin_info_e_x_t.html',1,'']]],
  ['vksamplelocationext_360',['VkSampleLocationEXT',['../struct_vk_sample_location_e_x_t.html',1,'']]],
  ['vksamplelocationsinfoext_361',['VkSampleLocationsInfoEXT',['../struct_vk_sample_locations_info_e_x_t.html',1,'']]],
  ['vksamplercreateinfo_362',['VkSamplerCreateInfo',['../struct_vk_sampler_create_info.html',1,'']]],
  ['vksamplerreductionmodecreateinfoext_363',['VkSamplerReductionModeCreateInfoEXT',['../struct_vk_sampler_reduction_mode_create_info_e_x_t.html',1,'']]],
  ['vksamplerycbcrconversioncreateinfo_364',['VkSamplerYcbcrConversionCreateInfo',['../struct_vk_sampler_ycbcr_conversion_create_info.html',1,'']]],
  ['vksamplerycbcrconversionimageformatproperties_365',['VkSamplerYcbcrConversionImageFormatProperties',['../struct_vk_sampler_ycbcr_conversion_image_format_properties.html',1,'']]],
  ['vksamplerycbcrconversioninfo_366',['VkSamplerYcbcrConversionInfo',['../struct_vk_sampler_ycbcr_conversion_info.html',1,'']]],
  ['vksemaphorecreateinfo_367',['VkSemaphoreCreateInfo',['../struct_vk_semaphore_create_info.html',1,'']]],
  ['vksemaphoregetfdinfokhr_368',['VkSemaphoreGetFdInfoKHR',['../struct_vk_semaphore_get_fd_info_k_h_r.html',1,'']]],
  ['vksemaphoregetwin32handleinfokhr_369',['VkSemaphoreGetWin32HandleInfoKHR',['../struct_vk_semaphore_get_win32_handle_info_k_h_r.html',1,'']]],
  ['vkshadermodulecreateinfo_370',['VkShaderModuleCreateInfo',['../struct_vk_shader_module_create_info.html',1,'']]],
  ['vkshadermodulevalidationcachecreateinfoext_371',['VkShaderModuleValidationCacheCreateInfoEXT',['../struct_vk_shader_module_validation_cache_create_info_e_x_t.html',1,'']]],
  ['vkshaderresourceusageamd_372',['VkShaderResourceUsageAMD',['../struct_vk_shader_resource_usage_a_m_d.html',1,'']]],
  ['vkshaderstatisticsinfoamd_373',['VkShaderStatisticsInfoAMD',['../struct_vk_shader_statistics_info_a_m_d.html',1,'']]],
  ['vksharedpresentsurfacecapabilitieskhr_374',['VkSharedPresentSurfaceCapabilitiesKHR',['../struct_vk_shared_present_surface_capabilities_k_h_r.html',1,'']]],
  ['vksparsebuffermemorybindinfo_375',['VkSparseBufferMemoryBindInfo',['../struct_vk_sparse_buffer_memory_bind_info.html',1,'']]],
  ['vksparseimageformatproperties_376',['VkSparseImageFormatProperties',['../struct_vk_sparse_image_format_properties.html',1,'']]],
  ['vksparseimageformatproperties2_377',['VkSparseImageFormatProperties2',['../struct_vk_sparse_image_format_properties2.html',1,'']]],
  ['vksparseimagememorybind_378',['VkSparseImageMemoryBind',['../struct_vk_sparse_image_memory_bind.html',1,'']]],
  ['vksparseimagememorybindinfo_379',['VkSparseImageMemoryBindInfo',['../struct_vk_sparse_image_memory_bind_info.html',1,'']]],
  ['vksparseimagememoryrequirements_380',['VkSparseImageMemoryRequirements',['../struct_vk_sparse_image_memory_requirements.html',1,'']]],
  ['vksparseimagememoryrequirements2_381',['VkSparseImageMemoryRequirements2',['../struct_vk_sparse_image_memory_requirements2.html',1,'']]],
  ['vksparseimageopaquememorybindinfo_382',['VkSparseImageOpaqueMemoryBindInfo',['../struct_vk_sparse_image_opaque_memory_bind_info.html',1,'']]],
  ['vksparsememorybind_383',['VkSparseMemoryBind',['../struct_vk_sparse_memory_bind.html',1,'']]],
  ['vkspecializationinfo_384',['VkSpecializationInfo',['../struct_vk_specialization_info.html',1,'']]],
  ['vkspecializationmapentry_385',['VkSpecializationMapEntry',['../struct_vk_specialization_map_entry.html',1,'']]],
  ['vkstencilopstate_386',['VkStencilOpState',['../struct_vk_stencil_op_state.html',1,'']]],
  ['vksubmitinfo_387',['VkSubmitInfo',['../struct_vk_submit_info.html',1,'']]],
  ['vksubpassbegininfokhr_388',['VkSubpassBeginInfoKHR',['../struct_vk_subpass_begin_info_k_h_r.html',1,'']]],
  ['vksubpassdependency_389',['VkSubpassDependency',['../struct_vk_subpass_dependency.html',1,'']]],
  ['vksubpassdependency2khr_390',['VkSubpassDependency2KHR',['../struct_vk_subpass_dependency2_k_h_r.html',1,'']]],
  ['vksubpassdescription_391',['VkSubpassDescription',['../struct_vk_subpass_description.html',1,'']]],
  ['vksubpassdescription2khr_392',['VkSubpassDescription2KHR',['../struct_vk_subpass_description2_k_h_r.html',1,'']]],
  ['vksubpassendinfokhr_393',['VkSubpassEndInfoKHR',['../struct_vk_subpass_end_info_k_h_r.html',1,'']]],
  ['vksubpasssamplelocationsext_394',['VkSubpassSampleLocationsEXT',['../struct_vk_subpass_sample_locations_e_x_t.html',1,'']]],
  ['vksubresourcelayout_395',['VkSubresourceLayout',['../struct_vk_subresource_layout.html',1,'']]],
  ['vksurfacecapabilities2ext_396',['VkSurfaceCapabilities2EXT',['../struct_vk_surface_capabilities2_e_x_t.html',1,'']]],
  ['vksurfacecapabilities2khr_397',['VkSurfaceCapabilities2KHR',['../struct_vk_surface_capabilities2_k_h_r.html',1,'']]],
  ['vksurfacecapabilitieskhr_398',['VkSurfaceCapabilitiesKHR',['../struct_vk_surface_capabilities_k_h_r.html',1,'']]],
  ['vksurfaceformat2khr_399',['VkSurfaceFormat2KHR',['../struct_vk_surface_format2_k_h_r.html',1,'']]],
  ['vksurfaceformatkhr_400',['VkSurfaceFormatKHR',['../struct_vk_surface_format_k_h_r.html',1,'']]],
  ['vkswapchaincountercreateinfoext_401',['VkSwapchainCounterCreateInfoEXT',['../struct_vk_swapchain_counter_create_info_e_x_t.html',1,'']]],
  ['vkswapchaincreateinfokhr_402',['VkSwapchainCreateInfoKHR',['../struct_vk_swapchain_create_info_k_h_r.html',1,'']]],
  ['vktexturelodgatherformatpropertiesamd_403',['VkTextureLODGatherFormatPropertiesAMD',['../struct_vk_texture_l_o_d_gather_format_properties_a_m_d.html',1,'']]],
  ['vkvalidationcachecreateinfoext_404',['VkValidationCacheCreateInfoEXT',['../struct_vk_validation_cache_create_info_e_x_t.html',1,'']]],
  ['vkvalidationflagsext_405',['VkValidationFlagsEXT',['../struct_vk_validation_flags_e_x_t.html',1,'']]],
  ['vkvertexinputattributedescription_406',['VkVertexInputAttributeDescription',['../struct_vk_vertex_input_attribute_description.html',1,'']]],
  ['vkvertexinputbindingdescription_407',['VkVertexInputBindingDescription',['../struct_vk_vertex_input_binding_description.html',1,'']]],
  ['vkvertexinputbindingdivisordescriptionext_408',['VkVertexInputBindingDivisorDescriptionEXT',['../struct_vk_vertex_input_binding_divisor_description_e_x_t.html',1,'']]],
  ['vkviewport_409',['VkViewport',['../struct_vk_viewport.html',1,'']]],
  ['vkviewportswizzlenv_410',['VkViewportSwizzleNV',['../struct_vk_viewport_swizzle_n_v.html',1,'']]],
  ['vkviewportwscalingnv_411',['VkViewportWScalingNV',['../struct_vk_viewport_w_scaling_n_v.html',1,'']]],
  ['vkvisurfacecreateinfonn_412',['VkViSurfaceCreateInfoNN',['../struct_vk_vi_surface_create_info_n_n.html',1,'']]],
  ['vkwaylandsurfacecreateinfokhr_413',['VkWaylandSurfaceCreateInfoKHR',['../struct_vk_wayland_surface_create_info_k_h_r.html',1,'']]],
  ['vkwin32keyedmutexacquirereleaseinfokhr_414',['VkWin32KeyedMutexAcquireReleaseInfoKHR',['../struct_vk_win32_keyed_mutex_acquire_release_info_k_h_r.html',1,'']]],
  ['vkwin32keyedmutexacquirereleaseinfonv_415',['VkWin32KeyedMutexAcquireReleaseInfoNV',['../struct_vk_win32_keyed_mutex_acquire_release_info_n_v.html',1,'']]],
  ['vkwin32surfacecreateinfokhr_416',['VkWin32SurfaceCreateInfoKHR',['../struct_vk_win32_surface_create_info_k_h_r.html',1,'']]],
  ['vkwritedescriptorset_417',['VkWriteDescriptorSet',['../struct_vk_write_descriptor_set.html',1,'']]],
  ['vkxcbsurfacecreateinfokhr_418',['VkXcbSurfaceCreateInfoKHR',['../struct_vk_xcb_surface_create_info_k_h_r.html',1,'']]],
  ['vkxlibsurfacecreateinfokhr_419',['VkXlibSurfaceCreateInfoKHR',['../struct_vk_xlib_surface_create_info_k_h_r.html',1,'']]],
  ['vkxycolorext_420',['VkXYColorEXT',['../struct_vk_x_y_color_e_x_t.html',1,'']]],
  ['void_20value_20not_20ignored_20as_20it_20ought_20to_20be_20what_20does_20this_20mean_421',['void value not ignored as it ought to be What does this mean',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md91',1,'My compiler complains &quot;void value not ignored as it ought to be.&quot; What does this mean?'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md590',1,'My compiler complains &quot;void value not ignored as it ought to be.&quot; What does this mean?']]],
  ['volumedown_422',['VolumeDown',['../structsf_1_1_keyboard_1_1_scan.html#aa42fbf6954d6f81f7606e566c7abe875af39be7065fce4f3b160cb75911fe60cd',1,'sf::Keyboard::Scan']]],
  ['volumemute_423',['VolumeMute',['../structsf_1_1_keyboard_1_1_scan.html#aa42fbf6954d6f81f7606e566c7abe875adb87d8a8e0bf729d7064a7e76e2f0f77',1,'sf::Keyboard::Scan']]],
  ['volumeup_424',['VolumeUp',['../structsf_1_1_keyboard_1_1_scan.html#aa42fbf6954d6f81f7606e566c7abe875aedd43e1542db23cd0cc496e60c0c5cbc',1,'sf::Keyboard::Scan']]],
  ['vorbis_5fblock_425',['vorbis_block',['../structvorbis__block.html',1,'']]],
  ['vorbis_5fcomment_426',['vorbis_comment',['../structvorbis__comment.html',1,'']]],
  ['vorbis_5fdsp_5fstate_427',['vorbis_dsp_state',['../structvorbis__dsp__state.html',1,'']]],
  ['vorbis_5fencode_5fctl_428',['vorbis_encode_ctl',['../build_2__deps_2sfml-src_2extlibs_2headers_2vorbis_2vorbisenc_8h.html#a5f398a378e20b8ce5e3341a582e773bd',1,'vorbis_encode_ctl(vorbis_info *vi, int number, void *arg):&#160;vorbisenc.h'],['../out_2build_2x64-_debug_2__deps_2sfml-src_2extlibs_2headers_2vorbis_2vorbisenc_8h.html#a5f398a378e20b8ce5e3341a582e773bd',1,'vorbis_encode_ctl(vorbis_info *vi, int number, void *arg):&#160;vorbisenc.h']]],
  ['vorbis_5fencode_5finit_429',['vorbis_encode_init',['../build_2__deps_2sfml-src_2extlibs_2headers_2vorbis_2vorbisenc_8h.html#a6571d9c349c540491256f1083e1ede71',1,'vorbis_encode_init(vorbis_info *vi, long channels, long rate, long max_bitrate, long nominal_bitrate, long min_bitrate):&#160;vorbisenc.h'],['../out_2build_2x64-_debug_2__deps_2sfml-src_2extlibs_2headers_2vorbis_2vorbisenc_8h.html#a6571d9c349c540491256f1083e1ede71',1,'vorbis_encode_init(vorbis_info *vi, long channels, long rate, long max_bitrate, long nominal_bitrate, long min_bitrate):&#160;vorbisenc.h']]],
  ['vorbis_5fencode_5finit_5fvbr_430',['vorbis_encode_init_vbr',['../build_2__deps_2sfml-src_2extlibs_2headers_2vorbis_2vorbisenc_8h.html#ab4e3d96c3008a29c615271d1f551c2a0',1,'vorbis_encode_init_vbr(vorbis_info *vi, long channels, long rate, float base_quality):&#160;vorbisenc.h'],['../out_2build_2x64-_debug_2__deps_2sfml-src_2extlibs_2headers_2vorbis_2vorbisenc_8h.html#ab4e3d96c3008a29c615271d1f551c2a0',1,'vorbis_encode_init_vbr(vorbis_info *vi, long channels, long rate, float base_quality):&#160;vorbisenc.h']]],
  ['vorbis_5fencode_5fsetup_5finit_431',['vorbis_encode_setup_init',['../build_2__deps_2sfml-src_2extlibs_2headers_2vorbis_2vorbisenc_8h.html#ac3953ff69d05864e78d1858a544ed619',1,'vorbis_encode_setup_init(vorbis_info *vi):&#160;vorbisenc.h'],['../out_2build_2x64-_debug_2__deps_2sfml-src_2extlibs_2headers_2vorbis_2vorbisenc_8h.html#ac3953ff69d05864e78d1858a544ed619',1,'vorbis_encode_setup_init(vorbis_info *vi):&#160;vorbisenc.h']]],
  ['vorbis_5fencode_5fsetup_5fmanaged_432',['vorbis_encode_setup_managed',['../build_2__deps_2sfml-src_2extlibs_2headers_2vorbis_2vorbisenc_8h.html#ac73714f24500e18024e83104e9e09485',1,'vorbis_encode_setup_managed(vorbis_info *vi, long channels, long rate, long max_bitrate, long nominal_bitrate, long min_bitrate):&#160;vorbisenc.h'],['../out_2build_2x64-_debug_2__deps_2sfml-src_2extlibs_2headers_2vorbis_2vorbisenc_8h.html#ac73714f24500e18024e83104e9e09485',1,'vorbis_encode_setup_managed(vorbis_info *vi, long channels, long rate, long max_bitrate, long nominal_bitrate, long min_bitrate):&#160;vorbisenc.h']]],
  ['vorbis_5fencode_5fsetup_5fvbr_433',['vorbis_encode_setup_vbr',['../build_2__deps_2sfml-src_2extlibs_2headers_2vorbis_2vorbisenc_8h.html#a0f7677f216936a6cd7fa28ddbccada74',1,'vorbis_encode_setup_vbr(vorbis_info *vi, long channels, long rate, float quality):&#160;vorbisenc.h'],['../out_2build_2x64-_debug_2__deps_2sfml-src_2extlibs_2headers_2vorbis_2vorbisenc_8h.html#a0f7677f216936a6cd7fa28ddbccada74',1,'vorbis_encode_setup_vbr(vorbis_info *vi, long channels, long rate, float quality):&#160;vorbisenc.h']]],
  ['vorbis_5finfo_434',['vorbis_info',['../structvorbis__info.html',1,'']]],
  ['vorbisenc_2eh_435',['vorbisenc.h',['../build_2__deps_2sfml-src_2extlibs_2headers_2vorbis_2vorbisenc_8h.html',1,'(Global Namespace)'],['../out_2build_2x64-_debug_2__deps_2sfml-src_2extlibs_2headers_2vorbis_2vorbisenc_8h.html',1,'(Global Namespace)']]],
  ['vs_20method_436',['Visual Studio (VS) method',['../md__r_e_a_d_m_e.html#autotoc_md1003',1,'']]],
  ['vs_20static_20runtimes_437',['vs Static Runtimes',['../dir_001a0f336d1d0a6c17b1be78e41a6b36.html#autotoc_md398',1,'Visual Studio Dynamic vs Static Runtimes'],['../dir_c3fcd705cb2f7b6b5193739f9f3f9966.html#autotoc_md897',1,'Visual Studio Dynamic vs Static Runtimes']]],
  ['vs_20unexpected_20calls_438',['Understanding Uninteresting vs Unexpected Calls',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#uninteresting-vs-unexpected',1,'']]],
  ['vulkan_439',['Vulkan',['../classsf_1_1_vulkan.html',1,'sf']]],
  ['vulkanexample_440',['VulkanExample',['../class_vulkan_example.html',1,'']]],
  ['vulkanimplwin32_441',['VulkanImplWin32',['../classsf_1_1priv_1_1_vulkan_impl_win32.html',1,'sf::priv']]],
  ['vulkanimplx11_442',['VulkanImplX11',['../classsf_1_1priv_1_1_vulkan_impl_x11.html',1,'sf::priv']]]
];
