var annotated_dup =
[
    [ "Pacman", null, [
      [ "Application", "class_pacman_1_1_application.html", "class_pacman_1_1_application" ],
      [ "GameScreen", "class_pacman_1_1_game_screen.html", "class_pacman_1_1_game_screen" ],
      [ "IMenuListener", "class_pacman_1_1_i_menu_listener.html", "class_pacman_1_1_i_menu_listener" ],
      [ "InputController", "class_pacman_1_1_input_controller.html", null ],
      [ "MenuScreen", "class_pacman_1_1_menu_screen.html", "class_pacman_1_1_menu_screen" ],
      [ "GameConfig", "struct_pacman_1_1_game_config.html", null ],
      [ "GameEngine", "class_pacman_1_1_game_engine.html", "class_pacman_1_1_game_engine" ],
      [ "GhostState", "struct_pacman_1_1_ghost_state.html", null ],
      [ "PlayerState", "struct_pacman_1_1_player_state.html", null ],
      [ "TileUpdate", "struct_pacman_1_1_tile_update.html", null ],
      [ "Vector2", "struct_pacman_1_1_vector2.html", null ],
      [ "Ghost", "class_pacman_1_1_ghost.html", "class_pacman_1_1_ghost" ],
      [ "GhostModeController", "class_pacman_1_1_ghost_mode_controller.html", "class_pacman_1_1_ghost_mode_controller" ],
      [ "BlueStrategy", "class_pacman_1_1_blue_strategy.html", null ],
      [ "IGhostStrategy", "class_pacman_1_1_i_ghost_strategy.html", "class_pacman_1_1_i_ghost_strategy" ],
      [ "OrangeStrategy", "class_pacman_1_1_orange_strategy.html", null ],
      [ "PinkStrategy", "class_pacman_1_1_pink_strategy.html", null ],
      [ "RedStrategy", "class_pacman_1_1_red_strategy.html", null ],
      [ "IEventListener", "class_pacman_1_1_i_event_listener.html", "class_pacman_1_1_i_event_listener" ],
      [ "IGameEngine", "class_pacman_1_1_i_game_engine.html", "class_pacman_1_1_i_game_engine" ],
      [ "IGhost", "class_pacman_1_1_i_ghost.html", "class_pacman_1_1_i_ghost" ],
      [ "Map", "class_pacman_1_1_map.html", null ]
    ] ],
    [ "ApplicationTest", "class_application_test.html", null ],
    [ "GameScreenTest", "class_game_screen_test.html", null ],
    [ "GhostModeControllerTest", "class_ghost_mode_controller_test.html", null ],
    [ "IGameEngineTest", "class_i_game_engine_test.html", null ],
    [ "IGhostTest", "class_i_ghost_test.html", null ],
    [ "InputControllerTest", "class_input_controller_test.html", null ],
    [ "MapTest", "class_map_test.html", null ],
    [ "MenuScreenTest", "class_menu_screen_test.html", null ],
    [ "MockEventListener", "class_mock_event_listener.html", null ],
    [ "MockGameEngine", "class_mock_game_engine.html", null ],
    [ "MockGhost", "class_mock_ghost.html", null ],
    [ "MockMenuListener", "class_mock_menu_listener.html", null ],
    [ "Vector2Test", "class_vector2_test.html", null ]
];